package decode

// The encoders below are the exact inverses of the decoders in this package.
//
// They exist for two reasons, and neither is symmetry for its own sake. Tests that
// plant a payload with the same scheme the detector reverses are self-describing:
// a failure says which scheme broke rather than which magic byte string changed.
// And the fixture generator uses them to build sample files, so the samples shipped
// with the tool are generated by the tool rather than copied from somewhere and
// trusted.
//
// Keeping them here rather than in a test file is deliberate: an inverse that lives
// beside its function stays correct when the function changes.

// EncodeTags hides a string in the Unicode Tag block.
func EncodeTags(s string) []rune {
	out := make([]rune, 0, len(s))
	for _, b := range []byte(s) {
		out = append(out, rune(0xE0000+int(b)))
	}
	return out
}

// EncodeVariationSelectors hides arbitrary bytes in variation selectors.
func EncodeVariationSelectors(b []byte) []rune {
	out := make([]rune, 0, len(b))
	for _, x := range b {
		if x < 16 {
			out = append(out, rune(0xFE00+int(x)))
		} else {
			out = append(out, rune(0xE0100+int(x)-16))
		}
	}
	return out
}

// EncodeZeroWidth hides bytes as zero-width characters, eight bits to the byte.
func EncodeZeroWidth(b []byte) []rune {
	out := make([]rune, 0, len(b)*8)
	for _, x := range b {
		for i := 7; i >= 0; i-- {
			if x>>uint(i)&1 == 1 {
				out = append(out, 0x200C)
			} else {
				out = append(out, 0x200B)
			}
		}
	}
	return out
}
