package c2pa_test

// These tests go through the engine rather than the package: a credential is only
// found if the container handler surfaces the block, the reassembly puts a split
// store back together, and the detector reads it. Each of those has been the thing
// that was wrong at some point, and none of them is visible from a unit test of
// the reader.

import (
	"archive/zip"
	"bytes"
	"encoding/base64"
	"encoding/binary"
	"strings"
	"testing"

	"github.com/dejo1307/augur/internal/detect/c2pa"
	"github.com/dejo1307/augur/internal/scan"
	"github.com/dejo1307/augur/pkg/finding"
)

func pngChunk(kind string, payload []byte) []byte {
	out := make([]byte, 4)
	binary.BigEndian.PutUint32(out, uint32(len(payload)))
	out = append(out, kind...)
	out = append(out, payload...)
	return append(out, 0, 0, 0, 0) // CRC: augur never verifies or rewrites it
}

// buildPNGWithCredential returns a PNG carrying a manifest store in its caBX
// chunk, with a hard binding that matches the file.
func buildPNGWithCredential(t *testing.T, generator, sourceType string) []byte {
	t.Helper()
	header := append([]byte("\x89PNG\r\n\x1a\n"), pngChunk("IHDR", make([]byte, 13))...)
	tail := append(pngChunk("IDAT", []byte{0x78, 0x9c, 0x03, 0x00}), pngChunk("IEND", nil)...)

	assemble := func(store []byte) ([]byte, [2]int) {
		chunk := pngChunk("caBX", store)
		file := append(append(append([]byte{}, header...), chunk...), tail...)
		return file, [2]int{len(header), len(header) + len(chunk)}
	}
	store := c2pa.SettleStore(t, assemble, generator, sourceType)
	file, _ := assemble(store)
	return file
}

func credential(t *testing.T, res scan.Result) (finding.Finding, bool) {
	t.Helper()
	for _, f := range res.Findings {
		if f.Kind == c2pa.KindManifest {
			return f, true
		}
	}
	return finding.Finding{}, false
}

func bindingRow(t *testing.T, f finding.Finding) string {
	t.Helper()
	table, ok := f.Detail.(finding.Table)
	if !ok {
		t.Fatalf("finding %q carries no table", f.Label)
	}
	for _, row := range table.Rows {
		if row.Key == "binding" {
			return row.Value
		}
	}
	return ""
}

func TestPNGCredentialIsReadAndItsBindingChecked(t *testing.T) {
	file := buildPNGWithCredential(t, "Some Generator", "trainedAlgorithmicMedia")

	res := scan.Scan("x.png", file)
	f, ok := credential(t, res)
	if !ok {
		t.Fatalf("no credential found in %d findings", len(res.Findings))
	}
	if !strings.Contains(f.Label, "Some Generator") || !strings.Contains(f.Label, "generated by a trained model") {
		t.Errorf("label = %q", f.Label)
	}
	if got := bindingRow(t, f); !strings.HasPrefix(got, "matches") {
		t.Errorf("binding = %q", got)
	}
}

func TestChangingOnePixelByteBreaksTheBinding(t *testing.T) {
	// This is the fact augur can establish about a Content Credential without a
	// key, a network or a trust list: the file is not the file that was signed.
	file := buildPNGWithCredential(t, "Some Generator", "")
	at := bytes.Index(file, []byte{0x78, 0x9c, 0x03, 0x00})
	if at < 0 {
		t.Fatal("fixture has no image data")
	}
	file[at+2] ^= 0xFF

	res := scan.Scan("x.png", file)
	var broken bool
	for _, f := range res.Findings {
		if f.Kind == c2pa.KindBroken {
			broken = true
			if f.Removable {
				t.Error("a mismatch is not something that can be removed")
			}
			if f.Severity != finding.Concern {
				t.Errorf("severity = %s", f.Severity)
			}
		}
	}
	if !broken {
		t.Fatal("a changed byte in the image data was not reported")
	}
}

func TestAStoreSplitAcrossJPEGSegmentsIsPutBackTogether(t *testing.T) {
	// A manifest store larger than 64 KB does not fit in one JPEG segment, so it
	// is split — and only the first piece is recognisable on its own. Reading the
	// pieces separately reports one credential augur cannot parse plus a handful
	// of unknown application segments, and no binding at all.
	assemble := func(store []byte) ([]byte, [2]int) {
		var segments []byte
		if len(store) > 0 {
			segments = buildAPP11Segments(splitStore(store))
		}
		file := append([]byte{0xFF, 0xD8}, segments...)
		file = append(file, 0xFF, 0xDA, 0x00, 0x05, 0x01, 0x01, 0x00)
		file = append(file, 0x12, 0x34, 0x56, 0x78, 0xFF, 0xD9)
		return file, [2]int{2, 2 + len(segments)}
	}

	// Settled by hand rather than with SettleStore: the segmenting means the
	// bytes the claim excludes are longer than the store itself.
	var store []byte
	for pass, bulk := 0, 90<<10; pass < 8; pass++ {
		file, at := assemble(store)
		next := c2pa.BulkyStoreFor(t, "Big Generator", bulk, file, at)
		settled := len(next) == len(store)
		store = next
		if settled {
			break
		}
	}
	if len(store) < 64<<10 {
		t.Fatalf("fixture store is only %d bytes; it must span segments", len(store))
	}
	file, _ := assemble(store)

	res := scan.Scan("x.jpg", file)
	var parts int
	var head finding.Finding
	for _, f := range res.Findings {
		if f.Kind == c2pa.KindManifest {
			parts++
			if !strings.Contains(f.Label, "continued") {
				head = f
			}
		}
		if f.Kind == "unknown-segment" {
			t.Errorf("a segment of the manifest was reported as unknown: %s", f.Label)
		}
	}
	if parts < 2 {
		t.Fatalf("the store spans %d segments but %d findings were reported", len(splitStore(store)), parts)
	}
	if !strings.Contains(head.Label, "Big Generator") {
		t.Fatalf("the reassembled store did not parse: %q", head.Label)
	}
	if got := bindingRow(t, head); !strings.HasPrefix(got, "matches") {
		t.Errorf("binding across reassembled segments = %q", got)
	}
}

// splitStore chops a manifest store into JPEG APP11 payloads the way a producer
// does: every segment repeats the eight-byte framing, and continuations repeat
// the box header as well.
func splitStore(store []byte) [][]byte {
	const max = 60 << 10
	var out [][]byte
	for i, at := 0, 0; at < len(store); i++ {
		payload := []byte{'J', 'P', 0x02, 0x11, 0, 0, 0, byte(i + 1)}
		if i > 0 {
			payload = append(payload, store[0:8]...) // LBox and TBox, repeated
		}
		end := at + max
		if end > len(store) {
			end = len(store)
		}
		payload = append(payload, store[at:end]...)
		out = append(out, payload)
		at = end
	}
	return out
}

func buildAPP11Segments(payloads [][]byte) []byte {
	var out []byte
	for _, p := range payloads {
		segment := []byte{0xFF, 0xEB, 0, 0}
		binary.BigEndian.PutUint16(segment[2:4], uint16(len(p)+2))
		out = append(out, append(segment, p...)...)
	}
	return out
}

func TestRemovingACredentialLeavesTheImageIntact(t *testing.T) {
	// A credential is metadata, and metadata is removable. What must not change is
	// anything else in the file.
	file := buildPNGWithCredential(t, "Some Generator", "")
	res := scan.Scan("x.png", file)
	f, ok := credential(t, res)
	if !ok {
		t.Fatal("no credential to remove")
	}

	out, err := scan.Apply(res.Source, res.Findings, []finding.ID{f.ID})
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(out, []byte("caBX")) {
		t.Error("the manifest chunk survived removal")
	}
	if !bytes.HasPrefix(out, []byte("\x89PNG\r\n\x1a\n")) || !bytes.Contains(out, []byte{0x78, 0x9c, 0x03, 0x00}) {
		t.Error("removing the credential damaged the image")
	}

	after := scan.Scan("x.png", out)
	if _, found := credential(t, after); found {
		t.Error("the credential is still reported after removal")
	}
}

func TestCredentialInAnSVGIsFoundAndRemovable(t *testing.T) {
	// An SVG is text, so this credential is found by a text detector, checked
	// against the document's own bytes, and removed by deleting an element — no
	// container rewrite anywhere in it.
	head := "<svg xmlns=\"http://www.w3.org/2000/svg\"><metadata><c2pa:manifest xmlns:c2pa=\"http://c2pa.org/manifest\">"
	tail := "</c2pa:manifest></metadata><rect width=\"10\" height=\"10\"/></svg>\n"

	assemble := func(store []byte) ([]byte, [2]int) {
		encoded := base64.StdEncoding.EncodeToString(store)
		return []byte(head + encoded + tail), [2]int{len(head), len(head) + len(encoded)}
	}
	// The base64 length grows in steps of four, so the settle loop works on the
	// encoded form rather than the store.
	var store []byte
	for pass := 0; pass < 8; pass++ {
		file, at := assemble(store)
		next := c2pa.StoreFor(t, "Vector Tool", "trainedAlgorithmicMedia", file, at)
		settled := len(next) == len(store)
		store = next
		if settled {
			break
		}
	}
	file, _ := assemble(store)

	res := scan.Scan("x.svg", file)
	f, ok := credential(t, res)
	if !ok {
		t.Fatalf("no credential found in %d findings", len(res.Findings))
	}
	if got := bindingRow(t, f); !strings.HasPrefix(got, "matches") {
		t.Errorf("binding = %q", got)
	}

	out, err := scan.Apply(res.Source, res.Findings, []finding.ID{f.ID})
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(out, []byte("c2pa:manifest")) {
		t.Error("the manifest element survived removal")
	}
	if !bytes.Contains(out, []byte("<rect width=\"10\"")) {
		t.Error("removal took the drawing with it")
	}
}

func TestCredentialInAWebPChunkIsFound(t *testing.T) {
	// The WebP container walker used to call every chunk it did not recognise
	// essential, which put a manifest in the same bucket as the pixels and hid it
	// from the detector entirely.
	assemble := func(store []byte) ([]byte, [2]int) {
		body := append([]byte("VP8 "), 0x04, 0, 0, 0, 1, 2, 3, 4)
		chunk := append([]byte("C2PA"), 0, 0, 0, 0)
		binary.LittleEndian.PutUint32(chunk[4:8], uint32(len(store)))
		chunk = append(chunk, store...)
		if len(store)%2 == 1 {
			chunk = append(chunk, 0)
		}
		file := append([]byte("RIFF"), 0, 0, 0, 0)
		file = append(file, "WEBP"...)
		at := len(file) + len(body)
		file = append(append(file, body...), chunk...)
		binary.LittleEndian.PutUint32(file[4:8], uint32(len(file)-8))
		return file, [2]int{at, at + len(chunk)}
	}
	store := c2pa.SettleStore(t, assemble, "Picture Tool", "")
	file, _ := assemble(store)

	res := scan.Scan("x.webp", file)
	f, ok := credential(t, res)
	if !ok {
		t.Fatalf("no credential found in %d findings", len(res.Findings))
	}
	if got := bindingRow(t, f); !strings.HasPrefix(got, "matches") {
		t.Errorf("binding = %q", got)
	}
}

func TestCredentialInAZipBasedDocumentIsRead(t *testing.T) {
	// A .docx keeps its credential as an archive part. Its binding is a hash over
	// every other part and the central directory, which augur does not recompute —
	// so the credential is read and the binding is named rather than claimed.
	store := c2pa.StoreFor(t, "Document Tool", "trainedAlgorithmicMedia", []byte("unused"))

	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	doc, err := zw.Create("word/document.xml")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := doc.Write([]byte("<w:document><w:body><w:t>hello</w:t></w:body></w:document>")); err != nil {
		t.Fatal(err)
	}
	part, err := zw.CreateHeader(&zip.FileHeader{Name: "META-INF/content_credential.c2pa", Method: zip.Store})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := part.Write(store); err != nil {
		t.Fatal(err)
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}

	res := scan.Scan("x.docx", buf.Bytes())
	f, ok := credential(t, res)
	if !ok {
		t.Fatalf("no credential found in %d findings", len(res.Findings))
	}
	if !strings.Contains(f.Label, "Document Tool") {
		t.Errorf("label = %q", f.Label)
	}
	if got := bindingRow(t, f); !strings.HasPrefix(got, "not checked") {
		t.Errorf("binding = %q, want an honest \"not checked\"", got)
	}
	if f.Removable {
		t.Error("nothing in a zip-based document is removable losslessly")
	}
}
