package c2pa

import (
	"encoding/binary"
	"strings"
	"testing"
)

func TestReadsWhatACredentialSays(t *testing.T) {
	store := buildStore(t, manifestOptions{
		claim: map[string]any{
			"claim_generator_info": []any{map[string]any{"name": "Test Generator", "version": "2.1"}},
			"dc:title":             "a document",
			"dc:format":            "text/plain",
			"alg":                  "sha256",
		},
		assertions: map[string]any{
			labelActions: map[string]any{"actions": []any{map[string]any{
				"action":            "c2pa.created",
				"softwareAgent":     "Some Model 1",
				"digitalSourceType": "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia",
			}}},
		},
	})

	report := Read(store, nil)
	if report.Err != nil {
		t.Fatal(report.Err)
	}
	if got := report.Summary(); got != "Test Generator 2.1, generated by a trained model" {
		t.Errorf("summary = %q", got)
	}

	rows := map[string]string{}
	for _, r := range report.Rows() {
		rows[r.Key] = r.Value
	}
	if rows["source"] != "generated by a trained model" {
		t.Errorf("the source row is the one people are looking for; got %q", rows["source"])
	}
	if rows["software agent"] != "Some Model 1" {
		t.Errorf("software agent = %q", rows["software agent"])
	}
	if rows["asset title"] != "a document" {
		t.Errorf("asset title = %q", rows["asset title"])
	}
}

func TestVersionedAssertionLabelsAreStillTheSameAssertion(t *testing.T) {
	// C2PA versions its labels in place: the actions assertion is "c2pa.actions"
	// in a v1 manifest and "c2pa.actions.v2" in a v2 one, and a second instance
	// of either is suffixed "__1". Matching the label exactly reports "no
	// actions" for most current files.
	for _, label := range []string{"c2pa.actions", "c2pa.actions.v2", "c2pa.actions__1", "c2pa.actions.v2__3"} {
		store := buildStore(t, manifestOptions{
			claimLabel: labelClaimV2,
			claim:      map[string]any{"claim_generator_info": map[string]any{"name": "Test"}},
			assertions: map[string]any{
				label: map[string]any{"actions": []any{map[string]any{"action": "c2pa.created"}}},
			},
		})
		s, err := Parse(store)
		if err != nil {
			t.Fatalf("%s: %v", label, err)
		}
		actions, ok := s.Active().Actions()
		if !ok || len(actions.Names) != 1 {
			t.Errorf("%s: actions not found", label)
		}
	}
}

func TestClaimVersionComesFromTheBoxLabel(t *testing.T) {
	v2 := buildStore(t, manifestOptions{
		claimLabel: labelClaimV2,
		claim:      map[string]any{"claim_generator_info": map[string]any{"name": "Test", "version": "1"}},
	})
	s, err := Parse(v2)
	if err != nil {
		t.Fatal(err)
	}
	if got := s.Active().ClaimVersion(); got != 2 {
		t.Errorf("claim version = %d, want 2", got)
	}
	if got := s.Active().Generator(); got != "Test 1" {
		t.Errorf("v2 generator info is a single map, not a list; got %q", got)
	}
}

func TestTheActiveManifestIsTheLastStandardOne(t *testing.T) {
	// An ingredient's manifest describes a different asset. Checking its binding
	// against this file would report a mismatch for a file nobody touched, so
	// which manifest is active is not a detail.
	ingredient := superBox("urn:uuid:ingredient", uuidManifest,
		superBox(labelAssertions, uuidAssertion),
		superBox(labelClaim, uuidClaim, contentBox(boxCBOR, cborEncodeIndefinite(
			map[string]any{"claim_generator": "the ingredient's tool"}))))
	active := superBox("urn:uuid:active", uuidManifest,
		superBox(labelAssertions, uuidAssertion),
		superBox(labelClaim, uuidClaim, contentBox(boxCBOR, cborEncodeIndefinite(
			map[string]any{"claim_generator": "this file's tool"}))))
	update := superBox("urn:uuid:update", uuidUpdate,
		superBox(labelAssertions, uuidAssertion),
		superBox(labelClaim, uuidClaim, contentBox(boxCBOR, cborEncodeIndefinite(
			map[string]any{"claim_generator": "an update manifest"}))))

	s, err := Parse(superBox(labelStore, uuidStore, ingredient, active, update))
	if err != nil {
		t.Fatal(err)
	}
	if got := s.Active().Generator(); got != "this file's tool" {
		t.Errorf("active manifest = %q", got)
	}
	if got := s.Ingredients(); got != 2 {
		t.Errorf("ingredients = %d, want 2", got)
	}
}

func TestBytesThatAreNotAStoreAreRefused(t *testing.T) {
	for name, input := range map[string][]byte{
		"empty":              {},
		"not a box":          []byte("hello there, this is just some text"),
		"a box of some kind": contentBox("junk", []byte("payload")),
		"a superbox that is not a manifest store": superBox("not.c2pa", uuidCBOR,
			contentBox(boxCBOR, cborEncode(map[string]any{"a": 1}))),
	} {
		if _, err := Parse(input); err == nil {
			t.Errorf("%s: parsed as a manifest store", name)
		}
		if StoreMagic(input) {
			t.Errorf("%s: passed the magic test", name)
		}
	}
}

func TestATruncatedStoreIsReportedRatherThanDropped(t *testing.T) {
	store := buildStore(t, manifestOptions{
		claim: map[string]any{"claim_generator": "tool 1.0"},
	})
	// Cut a box in half, and correct the outer length so the truncation is
	// inside the store rather than a lie about the store's own size.
	cut := append([]byte{}, store[:len(store)-40]...)
	binary.BigEndian.PutUint32(cut[0:4], uint32(len(cut)))

	s, err := Parse(cut)
	if err != nil {
		t.Fatalf("a truncated store should still report what it holds: %v", err)
	}
	if !s.Truncated {
		t.Error("truncation was not reported")
	}
	var said bool
	for _, row := range (Report{Store: s}).Rows() {
		if strings.Contains(row.Value, "truncated") {
			said = true
		}
	}
	if !said {
		t.Error("the rows do not mention that the store is cut short")
	}
}

func TestSourceTypeIsReadOutRatherThanQuoted(t *testing.T) {
	for uri, want := range map[string]string{
		"http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia":              "generated by a trained model",
		"http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia": "part generated by a trained model",
		"http://cv.iptc.org/newscodes/digitalsourcetype/digitalCapture":                       "captured by a camera or recorder",
		"": "",
		"http://cv.iptc.org/newscodes/digitalsourcetype/somethingNewNobodyHasSeen": "somethingNewNobodyHasSeen",
	} {
		if got := SourceType(uri); got != want {
			t.Errorf("SourceType(%q) = %q, want %q", uri, got, want)
		}
	}
}
