package c2pa

import (
	"fmt"
	"strings"
	"time"

	"github.com/dejo1307/augur/pkg/finding"
)

// Report is a manifest store reduced to what a detector shows a person: a table
// of what the credential says, and the one thing about it that can be checked.
//
// Every carrier — a JPEG segment, a PNG chunk, a WebP chunk, an SVG element, a
// PDF attachment, a zip entry — produces the same Report from the same bytes.
// That is the point of the split: finding a manifest is format work and reading
// one is not, so reading one is written once.
type Report struct {
	// Store is the parsed manifests, nil when the bytes would not parse.
	Store *Store
	// Binding is what could be established about the hard binding.
	Binding Binding
	// Err is why nothing could be read, when nothing could.
	Err error
}

// Read parses a manifest store and checks it against the file carrying it.
//
// `file` is the whole file the manifest was found in, because the exclusion
// ranges in a hard binding are absolute offsets into it. Pass nil when the
// manifest's bytes and the file's bytes are not in that relationship — a manifest
// inside a zip entry, say — and the binding is reported as unchecked rather than
// checked against the wrong bytes.
func Read(store, file []byte, carrier ...Extent) Report {
	s, err := Parse(store)
	if err != nil {
		return Report{Err: err}
	}
	r := Report{Store: s}
	if file == nil {
		r.Binding = Binding{Status: BindingUnchecked, Note: "not checked: the manifest is not addressed to these bytes"}
		if m := s.Active(); m != nil {
			if _, ok := m.Assertion(labelDataHash); !ok {
				r.Binding.Note = "not checked: no hash over the file as a whole"
			}
		}
		return r
	}
	if len(carrier) == 0 {
		r.Binding = Binding{
			Status: BindingUnchecked,
			Note:   "not checked: augur could not locate the manifest's own bytes in the file",
		}
		return r
	}
	r.Binding = s.Verify(file, carrier)
	return r
}

// Summary is the one-line description that goes after a finding's label: who the
// credential says made this, and what it says the source was. Empty when the
// manifest says neither.
func (r Report) Summary() string {
	if r.Store == nil {
		return ""
	}
	m := r.Store.Active()
	if m == nil {
		return ""
	}
	var parts []string
	if gen := m.Generator(); gen != "" {
		parts = append(parts, gen)
	}
	if actions, ok := m.Actions(); ok {
		if src := SourceType(actions.DigitalSourceType); src != "" {
			parts = append(parts, src)
		}
	}
	return strings.Join(parts, ", ")
}

// Rows renders the credential as the table a person decides against. The order is
// the order the questions get asked in: what made this, what does it say happened,
// who signed it, when, and does it still match the file.
func (r Report) Rows() []finding.KV {
	if r.Err != nil {
		return []finding.KV{{Key: "unreadable", Value: r.Err.Error()}}
	}
	m := r.Store.Active()
	if m == nil {
		return []finding.KV{{Key: "unreadable", Value: "the store holds no manifest"}}
	}

	var rows []finding.KV
	add := func(key, value string) {
		if value != "" {
			rows = append(rows, finding.KV{Key: key, Value: value})
		}
	}

	// Order is what a reader gets first, and the report line in a terminal is
	// truncated to a width — so the three rows that answer "what made this, and
	// does it still match" come before the ones that fill in the detail.
	add("generated by", m.Generator())
	actions, hasActions := m.Actions()
	if hasActions {
		if src := SourceType(actions.DigitalSourceType); src != "" {
			// The row that says the file came out of a model. Flagged, because it
			// is the one line in a credential most people are looking for.
			rows = append(rows, finding.KV{Key: "source", Value: src, Sensitive: true})
		}
	}
	rows = append(rows, r.bindingRow())

	if hasActions {
		if agent := actions.SoftwareAgent; agent != "" && agent != m.Generator() {
			add("software agent", agent)
		}
		add("actions", strings.Join(actions.Names, ", "))
		add("recorded time", actions.When)
	}

	add("asset title", cborString(cborGet(m.Claim, "dc:title")))
	add("asset format", cborString(cborGet(m.Claim, "dc:format")))

	if signer, ok := m.Signer(); ok {
		add("signed by", signer.Description())
		add("signature", signer.Algorithm)
		if !signer.TimeStamp.IsZero() {
			add("time-stamped", signer.TimeStamp.UTC().Format(time.RFC3339))
			// A countersigned time outside the signing certificate's validity is
			// the second thing in a credential that can be checked from the file
			// alone: the two statements it carries disagree with each other.
			if !signer.NotBefore.IsZero() &&
				(signer.TimeStamp.Before(signer.NotBefore) || signer.TimeStamp.After(signer.NotAfter)) {
				rows = append(rows, finding.KV{
					Key:       "certificate",
					Value:     "the time-stamp falls outside the certificate's validity window",
					Sensitive: true,
				})
			}
		}
		if signer.ChainLength > 1 {
			add("certificates", fmt.Sprintf("%d in the chain", signer.ChainLength))
		}
	} else if len(m.Signature) > 0 {
		add("signature", "present, but augur could not read it")
	} else {
		add("signature", "none in this manifest")
	}

	add("claim", fmt.Sprintf("version %d, %d assertions", m.ClaimVersion(), len(m.Assertions)))
	add("assertions", assertionList(m.Assertions))
	if n := r.Store.Ingredients(); n > 0 {
		add("ingredients", fmt.Sprintf("%d earlier manifest(s) for what went into this", n))
	}
	if r.Store.Truncated {
		rows = append(rows, finding.KV{
			Key: "store", Value: "ends mid-box: the manifest is truncated", Sensitive: true,
		})
	}
	return rows
}

// bindingRow states the checkable fact in the plainest words available.
func (r Report) bindingRow() finding.KV {
	switch r.Binding.Status {
	case BindingMatches:
		return finding.KV{
			Key:   "binding",
			Value: fmt.Sprintf("matches — the file still hashes to what was signed (%s)", r.Binding.Alg),
		}
	case BindingMismatch:
		return finding.KV{
			Key:       "binding",
			Value:     fmt.Sprintf("DOES NOT match — the file changed after it was signed (%s)", r.Binding.Alg),
			Sensitive: true,
		}
	case BindingAbsent:
		return finding.KV{
			Key:   "binding",
			Value: "none: this credential is not bound to the file's bytes",
		}
	default:
		note := r.Binding.Note
		if r.Binding.Kind != "" {
			note = r.Binding.Kind + ": " + note
		}
		return finding.KV{Key: "binding", Value: "not checked — " + note}
	}
}

// assertionList names the assertions without letting a manifest with two hundred
// of them take over the panel.
func assertionList(all []Assertion) string {
	const max = 12
	names := make([]string, 0, len(all))
	for _, a := range all {
		names = append(names, a.Label)
	}
	if len(names) > max {
		rest := len(names) - max
		names = append(names[:max], fmt.Sprintf("and %d more", rest))
	}
	return strings.Join(names, ", ")
}

// Mismatched reports whether the hard binding was checked and failed. It is the
// only condition in this package that warrants a finding of its own.
func (r Report) Mismatched() bool { return r.Binding.Status == BindingMismatch }
