package c2pa

import (
	"encoding/base64"
	"encoding/binary"
	"strings"
	"testing"

	"github.com/dejo1307/augur/pkg/detect"
	"github.com/dejo1307/augur/pkg/finding"
)

// wrapText encodes a manifest store the way the specification says unstructured
// text carries one: a zero-width no-break space, then one variation selector per
// byte of a wrapper that opens with a magic number.
func wrapText(store []byte) string {
	body := append([]byte{}, textWrapperMagic...)
	body = append(body, 1) // version
	length := make([]byte, 4)
	binary.BigEndian.PutUint32(length, uint32(len(store)))
	body = append(body, length...)
	body = append(body, store...)

	var b strings.Builder
	b.WriteRune(zeroWidthNoBreakSpace)
	for _, c := range body {
		if c < 16 {
			b.WriteRune(rune(0xFE00 + int(c)))
			continue
		}
		b.WriteRune(rune(0xE0100 + int(c) - 16))
	}
	return b.String()
}

func detectText(t *testing.T, data []byte) finding.Set {
	t.Helper()
	found, err := Text{}.Detect(&detect.Source{Bytes: data, Format: detect.Text})
	if err != nil {
		t.Fatal(err)
	}
	return found
}

func TestCredentialHiddenInTextIsReadRatherThanCounted(t *testing.T) {
	// Before this, a manifest in a paragraph of prose came out of augur as a run
	// of invisible characters that decoded to nothing readable. It is a signed
	// statement about where the text came from, and it names the model.
	visible := "Here is a paragraph of ordinary text.\n"
	claim := map[string]any{
		"claim_generator_info": []any{map[string]any{"name": "Some Assistant", "version": "5"}},
	}
	actions := map[string]any{"actions": []any{map[string]any{
		"action":            "c2pa.created",
		"softwareAgent":     "Some Assistant 5",
		"digitalSourceType": "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia",
	}}}

	// The wrapper's own bytes are what the claim excludes, and the wrapper's
	// length depends on the store's, so the two are settled together.
	// The wrapper's own bytes are what the claim excludes, and the wrapper's
	// length depends on the store's, so the two are settled together. The
	// placeholder's contents do not matter: they are inside the exclusion.
	var file []byte
	var wrapper string
	for size := 0; ; {
		placeholder := strings.Repeat("x", size)
		hash := dataHash([]byte(visible+placeholder), [2]int{len(visible), len(visible) + size})
		store := buildStore(t, manifestOptions{
			claim:      claim,
			assertions: map[string]any{labelDataHash: hash, labelActions: actions},
		})
		wrapper = wrapText(store)
		if len(wrapper) == size {
			file = []byte(visible + wrapper)
			break
		}
		size = len(wrapper)
	}

	found := detectText(t, file)
	if len(found) != 1 {
		t.Fatalf("findings = %d, want 1: %+v", len(found), found)
	}
	f := found[0]
	if f.Kind != KindManifest || f.Category != finding.Provenance {
		t.Errorf("kind = %s / %s", f.Kind, f.Category)
	}
	if !strings.Contains(f.Label, "generated by a trained model") {
		t.Errorf("label = %q", f.Label)
	}
	if !f.Removable {
		t.Error("a credential carried in text is exact bytes and should be removable")
	}
	if got := file[f.Span.Offset : f.Span.Offset+f.Span.Length]; string(got) != wrapper {
		t.Error("the span does not cover exactly the wrapper")
	}

	var binding string
	for _, row := range f.Detail.(finding.Table).Rows {
		if row.Key == "binding" {
			binding = row.Value
		}
	}
	if !strings.HasPrefix(binding, "matches") {
		t.Errorf("binding = %q", binding)
	}
}

func TestTextWithNoCredentialIsQuiet(t *testing.T) {
	// The detector must not fire on invisible characters in general: augur
	// already reports those, and calling every zero-width run a Content
	// Credential would be worse than not looking.
	for name, text := range map[string]string{
		"plain":                     "nothing here at all\n",
		"a zero-width space":        "some\u200btext\n",
		"variation selectors alone": "text\uFE00\uFE01\uFE02 more\n",
		"a no-break space and then selectors that decode to nothing": "\uFEFF\uFE00\uFE01\n",
	} {
		if found := detectText(t, []byte(text)); len(found) != 0 {
			t.Errorf("%s: reported %d findings", name, len(found))
		}
	}
}

func TestManifestBlockInAComment(t *testing.T) {
	store := buildStore(t, manifestOptions{
		claim: map[string]any{"claim_generator": "block tool 1.0"},
	})
	body := "# -----BEGIN C2PA MANIFEST----- data:application/c2pa;base64," +
		base64.StdEncoding.EncodeToString(store) + " -----END C2PA MANIFEST-----\nprint('hello')\n"

	found := detectText(t, []byte(body))
	if len(found) != 1 || found[0].Kind != KindManifest {
		t.Fatalf("findings = %+v", found)
	}
	if !strings.Contains(found[0].Label, "block tool 1.0") {
		t.Errorf("label = %q", found[0].Label)
	}
}

func TestManifestBlockPointingElsewhereIsReportedAsAReference(t *testing.T) {
	// A credential kept at a URL is a different situation from one carried in the
	// file: augur fetches nothing, so what it says is not knowable here.
	body := "// -----BEGIN C2PA MANIFEST----- https://example.com/a1b2c3.c2pa -----END C2PA MANIFEST-----\n"

	found := detectText(t, []byte(body))
	if len(found) != 1 || found[0].Kind != KindReference {
		t.Fatalf("findings = %+v", found)
	}
	var url string
	for _, row := range found[0].Detail.(finding.Table).Rows {
		if row.Key == "manifest at" {
			url = row.Value
		}
	}
	if url != "https://example.com/a1b2c3.c2pa" {
		t.Errorf("manifest URL = %q", url)
	}
}

func TestCredentialInAnHTMLDocument(t *testing.T) {
	store := buildStore(t, manifestOptions{claim: map[string]any{"claim_generator": "page tool 2.0"}})
	page := "<!DOCTYPE html>\n<html><head>\n<script type=\"application/c2pa\">\n" +
		base64.StdEncoding.EncodeToString(store) + "\n</script>\n</head><body><p>hi</p></body></html>\n"

	found := detectText(t, []byte(page))
	if len(found) != 1 || !strings.Contains(found[0].Label, "page tool 2.0") {
		t.Fatalf("findings = %+v", found)
	}
	if got := page[found[0].Span.Offset : found[0].Span.Offset+found[0].Span.Length]; !strings.HasPrefix(got, "<script") ||
		!strings.HasSuffix(got, "</script>") {
		t.Errorf("the span should cover the whole element; got %.20q…", got)
	}
}

func TestHTMLLinkToAManifestIsAReference(t *testing.T) {
	page := `<html><head><link rel="c2pa-manifest" href="https://example.com/m.c2pa" type="application/c2pa"></head></html>`
	found := detectText(t, []byte(page))
	if len(found) != 1 || found[0].Kind != KindReference {
		t.Fatalf("findings = %+v", found)
	}
}

func TestNormalisationSensitiveTextIsNotAccused(t *testing.T) {
	// The hash for this carrier is defined over NFC-normalised text. Where
	// normalising could change a byte, augur has no way to know whether a
	// mismatch means the text was edited or merely stored differently — so it
	// declines to check rather than reporting a change that may not have
	// happened.
	if !nfcSafe([]byte("plain ascii and even \u00e9moji \u00e9"), Extent{}) {
		t.Error("precomposed text is NFC-safe")
	}
	if nfcSafe([]byte("e\u0301 is e plus an accent"), Extent{}) {
		t.Error("a combining mark makes normalisation consequential")
	}
	if nfcSafe([]byte("\ud55c\u1100"), Extent{}) {
		t.Error("Hangul jamo compose")
	}
}
