package tui

import (
	"strings"
	"testing"
	"time"

	"github.com/charmbracelet/lipgloss"
	"github.com/dejo1307/augur/pkg/finding"
)

// The viewer's detail panel has no horizontal scroll: a line wider than the
// panel is not clipped with an ellipsis that says so, it is simply gone off the
// edge. So the property worth pinning is a plain one — nothing rendered into a
// panel of width N is wider than N — and it is worth pinning because the
// interesting rows are the long ones. "binding: matches — the file still hashes
// to what was signed" is the line a reader of a Content Credential came for, and
// it was being cut mid-clause.

const panel = 60

func widest(rendered string) (int, string) {
	worst, at := 0, ""
	for _, line := range strings.Split(rendered, "\n") {
		if w := lipgloss.Width(line); w > worst {
			worst, at = w, line
		}
	}
	return worst, at
}

func tableFinding(rows ...finding.KV) finding.Finding {
	f := finding.New("test", "kind", finding.Provenance, finding.Notice,
		finding.Span{Offset: 0, Length: 1, Exact: true},
		"a finding", "why it is here")
	return f.WithDetail(finding.NewTable("c2pa", rows))
}

func TestALongRowIsWrappedRatherThanCut(t *testing.T) {
	f := tableFinding(finding.KV{
		Key:   "binding",
		Value: "matches — the file still hashes to what the claim signed (sha256)",
	})

	out := renderDetail(f, panel)
	if w, line := widest(out); w > panel {
		t.Fatalf("a line is %d columns wide in a %d-column panel: %q", w, panel, line)
	}
	if !strings.Contains(out, "sha256") {
		t.Error("the end of the row did not survive wrapping")
	}
}

func TestAValueWithNoSpacesIsBrokenUp(t *testing.T) {
	// A URL, a document ID, a hash. Nothing in it is a place to break a line, so
	// a wrapper that only splits on spaces emits it whole and the panel eats
	// whatever does not fit.
	const url = "https://manifests.example.com/store/a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8.c2pa"
	out := renderDetail(tableFinding(finding.KV{Key: "manifest at", Value: url}), panel)

	if w, line := widest(out); w > panel {
		t.Fatalf("a line is %d columns wide in a %d-column panel: %q", w, panel, line)
	}
	// Every character of it is still there, in order, once the wrapping is undone.
	flat := strings.ReplaceAll(strings.ReplaceAll(out, "\n", ""), " ", "")
	if !strings.Contains(flat, strings.ReplaceAll(url, " ", "")) {
		t.Errorf("the value did not survive being broken up:\n%s", out)
	}
}

func TestWideCharactersAreMeasuredInColumns(t *testing.T) {
	// A character is not a column. CJK occupies two, so counting runes lets a
	// line of Japanese overflow the panel by nearly double — on precisely the
	// text a Unicode inspector is pointed at.
	value := strings.Repeat("日本語のテキスト", 6)
	out := renderDetail(tableFinding(finding.KV{Key: "comment", Value: value}), panel)

	if w, line := widest(out); w > panel {
		t.Fatalf("a line is %d columns wide in a %d-column panel: %q", w, panel, line)
	}
}

func TestALongLabelWrapsToo(t *testing.T) {
	f := finding.New("test", "kind", finding.Provenance, finding.Notice,
		finding.Span{Offset: 0, Length: 1, Exact: true},
		"C2PA Content Credential (1.5 kB) — Aperture Studio 3.2, generated by a trained model",
		"why it is here")

	out := renderDetail(f, panel)
	if w, line := widest(out); w > panel {
		t.Fatalf("a line is %d columns wide in a %d-column panel: %q", w, panel, line)
	}
	if !strings.Contains(out, "generated by a trained model") {
		t.Error("the end of the label was lost")
	}
}

func TestWrapKeepsTheWordsItWasGiven(t *testing.T) {
	const text = "the quick brown fox jumps over the lazy dog and keeps going for a while"
	got := strings.Fields(wrap(text, 20))
	want := strings.Fields(text)
	if len(got) != len(want) {
		t.Fatalf("wrapping changed the word count: %d, want %d", len(got), len(want))
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("word %d is %q, want %q", i, got[i], want[i])
		}
	}
}

func TestWrapTerminatesOnAWidthNarrowerThanOneCharacter(t *testing.T) {
	// Not a real panel size, but a wrapper that loops forever on one is a hang in
	// a program somebody is running on a file they do not trust.
	done := make(chan string, 1)
	go func() { done <- wrap(strings.Repeat("日", 20), 1) }()
	select {
	case out := <-done:
		if strings.Count(out, "\n") == 0 {
			t.Error("nothing was broken up at all")
		}
	case <-time.After(2 * time.Second):
		t.Fatal("wrap did not terminate")
	}
}

func TestTruncateCountsColumnsNotCharacters(t *testing.T) {
	// The findings list is a fixed-width pane beside the detail panel. A label
	// truncated by character count is up to twice as wide as it was allowed to
	// be when the label is CJK, and the pane it overflows is somebody else's.
	for _, s := range []string{
		"日本語のテキストがとても長い場合のラベル",
		"a plain ascii label that is quite long indeed",
		"mixed ラベル with both kinds of character in it",
	} {
		for _, n := range []int{8, 20, 32} {
			got := truncate(s, n)
			if w := lipgloss.Width(got); w > n {
				t.Errorf("truncate(%q, %d) is %d columns: %q", s, n, w, got)
			}
		}
	}
}

func TestTruncateLeavesShortStringsAlone(t *testing.T) {
	if got := truncate("short", 20); got != "short" {
		t.Errorf("truncate added something: %q", got)
	}
}
